#Nome microservico GATEWAY
spring:
  application:
    name: mscloudgateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

#Porta server GATEWAY
server:
  port: 8080

#Localizacao do Discovery EUREKA para registrar o GATEWAY
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-user:ZXVyZWthLXVzZXI=@localhost:8761/eureka